# Matrix Multiplication

## Multiplying 2x2 matrices:

Multiplying 2x2 matrices:

$$\begin{bmatrix}A & B\\C & D\end{bmatrix} * 
\begin{bmatrix}E & F\\G & H\end{bmatrix} =
\begin{bmatrix}(AE + BG) & (AF + BH)\\(CE + DG) & (CF + DH)\end{bmatrix}
$$

Gives you another 2x2 matrix as a result.

Given the matrix multiplication below
$$\begin{bmatrix}1 & 2\\3 & 4\end{bmatrix} * 
\begin{bmatrix}9 & 8\\7 & 6\end{bmatrix} =
\begin{bmatrix}((1*9) + (2*7)) & ((1*8) + (2*6))\\((3*9) + (4*7)) & ((3*8) + (4*6))\end{bmatrix} =
\begin{bmatrix}((9 + 14) & (8 + 12)\\(27 + 28) & (24 + 24)\end{bmatrix}
\begin{bmatrix}23 & 20\\55 & 48\end{bmatrix}
$$

We will create R code to perform the multiplication

In [7]:
# Define and print a matrix
mat1 <- matrix(c(1,2,3,4), nrow=2, byrow=T)
print("mat1 is: ", mat1)

# Define and print another matrix
mat2 <- matrix(c(9,8,7,6), nrow=2, byrow=T)
print(mat2)

# Multiply and print the result
result <- mat1 %*% mat2
print(result)

[1] "mat1 is: "
     [,1] [,2]
[1,]    9    8
[2,]    7    6
     [,1] [,2]
[1,]   23   20
[2,]   55   48
     [,1] [,2]
[1,]    9   16
[2,]   21   24


## Multiplying a 1x2 with a 2x2 matrix:

$$
\begin{bmatrix}A & B\end{bmatrix} * 
\begin{bmatrix}C & D\\E & F\end{bmatrix} =
\begin{bmatrix}(AC + BE) & (AD + BF)\end{bmatrix}
$$

Gives you a 1x2 matrix as a result.

# References

DataCamp.com. (n.d.). R Documentation - Matrix. Retrieved December 05, 2020, from https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/matrix

Mathisfun.com. (2017). Retrieved December 05, 2020, from https://www.mathsisfun.com/algebra/matrix-introduction.html

MathJax Demos. (n.d.). Retrieved December 05, 2020, from https://mathjax.github.io/MathJax-demos-web/